language: "php"

php: 
- 5.4
- 5.5
- "hhvm"

before_script: 
- "wget http://getcomposer.org/composer.phar"
- "wget https://phar.phpunit.de/phpunit.phar"
- "php composer.phar install --dev --no-interaction"

script: 
- "mkdir -p build/logs"
- "php phpunit.phar --coverage-clover build/logs/clover.xml ."

after_script: 
- "mkdir -p build/coverage"
- "echo '{\"require-dev\": {\"satooshi/php-coveralls\": \"dev-master\"}}' > build/coverage/composer.json"
- "echo 'src_dir: ../../src/' >> build/coverage/.coveralls.yml"
- "echo 'coverage_clover: ../../build/logs/clover.xml' >> build/coverage/.coveralls.yml"
- "echo 'json_path: ../../build/logs/coveralls-upload.json' >> build/coverage/.coveralls.yml"
- "cd build/coverage"
- "php ../../composer.phar install --dev --no-interaction"
- "cd ../../"
- sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ] php build/coverage/vendor/bin/coveralls -v'
